version: "3.9"

services:
  client_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - $PWD:/home/node/client_app
    restart: always
    environment:
      NEXT_PUBLIC_AUTH_URL: http://127.0.0.1:3000
      NEXTAUTH_URL: http://127.0.0.1:3000

      NEXT_PUBLIC_WEB_API_URL: http://localhost:3050/api/v1

      NEXTAUTH_SECRET: secret_strong_1234_PGBPZP5AS9HVCDSPT7Y2NMSWP4NA4NSLC

    command: sh -c './entrypoint.dev.sh'
